// Fill out your copyright notice in the Description page of Project Settings.


#include "BacteriaBase.h"
#include "Kismet/GameplayStatics.h"
#include "Components/StaticMeshComponent.h"
#include "UObject/ConstructorHelpers.h"
#include "StageManager.h"

ABacteriaBase::ABacteriaBase()
{
    PrimaryActorTick.bCanEverTick = true;

    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
    RootComponent = MeshComponent;

    MeshComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    MeshComponent->SetCollisionObjectType(ECC_GameTraceChannel1); // "Bacteria" Ă¤łÎ

    MeshComponent->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);

    MeshComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Ignore); // Ľ­·Î ą«˝Ă

    MeshComponent->SetEnableGravity(false);
    MeshComponent->SetSimulatePhysics(true);

    ShieldMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ShieldMesh"));
    ShieldMesh->SetupAttachment(RootComponent);

    static ConstructorHelpers::FObjectFinder<UStaticMesh> ShieldAsset(TEXT("/Game/Niagara/Shield/IcoSphere.IcoSphere")); // ˝ÇÁ¦ °ć·Î·Î!
    if (ShieldAsset.Succeeded())
    {
        ShieldMesh->SetStaticMesh(ShieldAsset.Object);
    }

    DeathEffect = LoadObject<UNiagaraSystem>(
        nullptr,
        TEXT("/Game/Niagara/NS_Cloud.NS_Cloud")
    );

    // ĂĘ±â ĂĽ·Â
    Health = 100.0f;
    ShieldHP = 0.f;
}

float ABacteriaBase::getHealth()
{
    return Health;
}

void ABacteriaBase::BeginPlay()
{
    Super::BeginPlay();

    AStageManager* StageManager = Cast<AStageManager>(UGameplayStatics::GetActorOfClass(GetWorld(), AStageManager::StaticClass()));
    if (StageManager)
    {
        StageManager->RegisterBacteria(this);
    }
    // ¸ÓĆĽ¸®ľó/˝şÄÉŔĎ/Ŕ§Äˇ/Ĺő¸íµµ µî Ăß°ˇ ĽĽĆĂ
    ShieldMesh->SetVisibility(Shield); // ĂłŔ˝żŁ ľČ ş¸ŔĚ°Ô
    ShieldMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision); // Ăćµą X
    ShieldMesh->SetWorldScale3D(GetActorScale3D() * 2.f); // ş»ĂĽş¸´Ů Á¶±Ý Ĺ©°Ô

    LaunchBounce();
    ChildBegin();
}

void ABacteriaBase::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    if (CurrentState == EBacteriaState::CustomBehavior) {
        performBehavior(DeltaTime);
        if (PistolOverlap)
        {
            GetWorld()->GetTimerManager().SetTimer(
                SpawnTimerHandle, this,
                &ABacteriaBase::TakeDamageBacPistol,
                0.1f, true
            );
            PistolOverlap = false;
        }
    }
}

void ABacteriaBase::ClearTimer()
{
    GetWorld()->GetTimerManager().ClearTimer(SpawnTimerHandle);
}

void ABacteriaBase::HitBac(AActor* Actor)
{
    float HitDamage = 0.f;
    if (Actor->Tags.Contains("Bullet0")) {
        HitDamage = 50.f;
        Actor->Destroy();
    }
    else if (Actor->Tags.Contains("Bullet1")) HitDamage = 30.f;
    else if (Actor->Tags.Contains("Bullet2")) {
        HitDamage = 30.f;
        Actor->Destroy();
    }
    else if (Actor->ActorHasTag("Pistol")) {
        PistolOverlap = true;
    }
    else return;
    
    if (bShieldHitRecently) return;
    TakeDamageBac(HitDamage);
}

void ABacteriaBase::TakeDamageBac(float HitDamage)
{
    float TempDam = ShieldHP - HitDamage;
    if (TempDam > 0.f) {
        ShieldHP = TempDam;
    }
    else {
        bShieldHitRecently = true;
        ShieldMesh->SetHiddenInGame(true);
        GetWorldTimerManager().SetTimerForNextTick([this]()
            {
                bShieldHitRecently = false;
            });
        Shield = false;
        Health += TempDam;
        if (Health <= 0.f) {
            OnDeath();
            if (DeathEffect) {
                UNiagaraFunctionLibrary::SpawnSystemAtLocation(
                    GetWorld(),
                    DeathEffect,
                    GetActorLocation()
                );
            }
            Destroy();
        }
    }
}

void ABacteriaBase::TakeDamageBacPistol()
{
    TakeDamageBac(5.f);
}

void ABacteriaBase::Destroyed()
{
    Super::Destroyed();

    AStageManager* StageManager = Cast<AStageManager>(UGameplayStatics::GetActorOfClass(GetWorld(), AStageManager::StaticClass()));
    if (StageManager)
    {
        StageManager->UnregisterBacteria(this);
    }
}

void ABacteriaBase::performBehavior(float DeltaTime)
{
    if (CameraComp) {
        PlayerLocation = CameraComp->GetComponentLocation();
    }
}

void ABacteriaBase::LaunchBounce()
{
    float X = FMath::FRandRange(XRangeMin, XRangeMax);
    float Y = FMath::FRandRange(YRangeMin, YRangeMax);

    FVector BounceDir;
    if (GetActorLocation().Z > 0.0f) {
        BounceDir = FVector(X, Y, UptoDownRate);
        SetActorRotation(FRotator(-180.f, 0, 0));
    }
    else {
        BounceDir = FVector(X, Y, DownToUpRate);
    }
    MeshComponent->AddImpulse(BounceDir * Force * Impulse, NAME_None, true);

    GetWorldTimerManager().SetTimerForNextTick([this]()
        {
            CurrentState = EBacteriaState::CustomBehavior;
        });
}

void ABacteriaBase::Init(APawn* InPlayer, float InUptoDownRate, float InDownToUpRate, float InForce, float InXRangeMin, float InXRangeMax, float InYRangeMin, float InYRangeMax)
{
    PlayerPawn = InPlayer;
    if (PlayerPawn)
    {
        CameraComp = PlayerPawn->FindComponentByClass<UCameraComponent>();
    }

    this->UptoDownRate = InUptoDownRate;
    this->DownToUpRate = InDownToUpRate;
    this->Force = InForce;
    this->XRangeMin = InXRangeMin;
    this->XRangeMax = InXRangeMax;
    this->YRangeMin = InYRangeMin;
    this->YRangeMax = InYRangeMax;
}
