// Fill out your copyright notice in the Description page of Project Settings.
// Fill out your copyright notice in the Description page of Project Settings.


#include "StageManager.h"
#include <Kismet/GameplayStatics.h>

// Sets default values
AStageManager::AStageManager()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
}

// Called when the game starts or when spawned
void AStageManager::BeginPlay()
{
	Super::BeginPlay();

	// 3초 후 Stage 시작
	if(Start) GetWorldTimerManager().SetTimer(DelayStartHandle, this, &AStageManager::StartFirstStage, 3.0f, false);
}

void AStageManager::RegisterBacteria(ABacteriaBase* Bacteria)
{
	if (Bacteria && !RegisteredBacteria.Contains(Bacteria))
	{
		RegisteredBacteria.Add(Bacteria);
	}
	Bacteria->OnPlayerAttacked.AddDynamic(this, &AStageManager::HandlePlayerAttacked);
}

void AStageManager::UnregisterBacteria(ABacteriaBase* Bacteria)
{
	if (Bacteria)
	{
		UE_LOG(LogTemp, Warning, TEXT("Destroyed: %s"), *Bacteria->GetName());
		RegisteredBacteria.Remove(Bacteria);
	}
}

void AStageManager::HandlePlayerAttacked(ABacteriaBase* Attacker)
{
	UE_LOG(LogTemp, Warning, TEXT("플레이어가 박테리아에게 공격당함!"));
	float Damage = Attacker->AttackPower;
	OnPlayerAttackedBP(Damage); // 블루프린트 연출 호출
}

// Called every frame
void AStageManager::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (!bStageStarted) return; // 3초 딜레이 전에는 아무것도 안 함

	if(!bCleared) Time += DeltaTime;

	if (StageNum == 1 && Time > 30.f) {
		SpawnEnemy();
	}
	else if (StageNum == 2 && Time > 60.f) {
		SpawnEnemy();
	}

	if (bAllSpawned && RegisteredBacteria.IsEmpty()) {
		/*
		UMyGameInstance* GI = Cast<UMyGameInstance>(GetGameInstance());
		if (GI) {
			GI->bStageCleared = true;
		}
		*/
		bCleared = true;
		UE_LOG(LogTemp, Warning, TEXT("GameClear"));
		GameClear();
	}
}

void AStageManager::StartFirstStage()
{
	// Stage1 시작 시점에서 Time 초기화 및 스폰
	Time = 0.f;
	StageNum = 0;
	bStageStarted = true;

	SpawnEnemy();
}

void AStageManager::SpawnNextEnemy()
{
	FVector2D Rand2D = FMath::RandPointInCircle(SpawnRadius);
	FVector Offset(Rand2D.X, Rand2D.Y, 0.f);
	FVector SpawnLoc = SpawnPoint[FMath::RandRange(0, SpawnPointNum)] + Offset;
	FRotator RandomRot = FRotator(0, 0, 0);
	ABacteriaBase* SpawnedBacteria = GetWorld()->SpawnActorDeferred<ABacteriaBase>(
		Enemy[0],
		FTransform(RandomRot, SpawnLoc),
		this,
		nullptr,
		ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn
		);
	if (SpawnedBacteria) {
		SpawnedBacteria->Init(PlayerPawn, UptoDownRate, DownToUpRate, Force, XRangeMin, XRangeMax, YRangeMin, YRangeMax);
		UGameplayStatics::FinishSpawningActor(SpawnedBacteria, FTransform(RandomRot, SpawnLoc));
	}
	if (NiagaraEffect)
	{
		// 2. 원하는 위치에 이펙트 생성
		UNiagaraFunctionLibrary::SpawnSystemAttached(
			NiagaraEffect,             // 나이아가라 시스템
			SpawnedBacteria->GetRootComponent(),             // 어태치할 컴포넌트 (ex: RootComponent)
			NAME_None,                 // 소켓 이름 (없으면 NAME_None)
			FVector::ZeroVector,       // 위치 오프셋
			FRotator::ZeroRotator,     // 회전 오프셋
			EAttachLocation::KeepRelativeOffset, // 어태치 방식
			true                       // 파괴 시 자동 삭제 여부
		);
	}
	Enemy.RemoveAt(0);

	if (Enemy.Num() <= 0)
	{
		if (StageNum == 2) bAllSpawned = true;
		MonsterInfo();
		GetWorld()->GetTimerManager().ClearTimer(SpawnTimerHandle);
	}
}

void AStageManager::PickEnemyInfo()
{
	FEnemyInfo* EnemyInfo = nullptr;
	if (EnemyDataTable) {
		TArray<FName> RowNames = EnemyDataTable->GetRowNames();
		if (RowNames.Num() > 0) {
			int32 RandomIndex = FMath::RandRange(0, RowNames.Num() - 1);
			FName RandomRowName = RowNames[RandomIndex];
			EnemyInfo = EnemyDataTable->FindRow<FEnemyInfo>(RandomRowName, TEXT(""));
		}
	}
	for (int i = 0; i < EnemyInfo->Enemy1Count; i++) Enemy.Add(EnemyInfo->Enemy1);
	for (int i = 0; i < EnemyInfo->Enemy2Count; i++) Enemy.Add(EnemyInfo->Enemy2);
}

void AStageManager::SpawnEnemy()
{
	StageNum++;
	SpawnOrigin = GetActorLocation() + FVector(0.f, 0.f, 1400.f);

	/*
	// 스폰 범위 시각화
	DrawDebugSphere(
		GetWorld(),
		SpawnOrigin,
		SpawnRadius,
		32,
		FColor::Green,
		true,   // Persistent
		-1.f,   // LifeTime (무제한)
		0,
		2.f     // Thickness
	);
	*/
	//EnemyClass2 = Enemy2;
	//Count2 = Enemy2Count;

	//SpawnPhase = 1; // 1단계: Enemy1
	//TotalSpawnCount = Count1;

	GetWorld()->GetTimerManager().SetTimer(
		SpawnTimerHandle, this,
		&AStageManager::SpawnNextEnemy,
		1.0f, true
	);
}


void AStageManager::TickDisable()
{
	for (ABacteriaBase* Bacteria : RegisteredBacteria)
	{
		if (IsValid(Bacteria))
		{
			Bacteria->SetActorTickEnabled(false); // 또는 Bacteria->MoveSpeed = 0.f;
		}
	}
}
